# fly.toml app configuration file generated for vicf-dry-sun-877 on 2025-10-18T22:05:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vicf'
primary_region = 'lhr'

[build]
  command = "cd ./frontend && yarn && yarn build && cd ../backend && yarn && yarn build && mkdir -p ./dist/client && cp -r ../frontend/dist/* ./dist/client/"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1