services:
  - type: web
    name: my-backend
    env: node
    rootDir: backend
    buildCommand: |
      cd ../frontend
      npm ci
      npm run build
      cp -r build ../backend/client
      cd ../backend
      npm ci
    startCommand: node dist/index.js # or your start script
